// AUTO-GENERATED from prototype/index.html (curated dataset only).
// Generated by tmp_extract.cjs during Phase A. Safe to edit by hand later;
// the generated/variant engine from the prototype is intentionally excluded
// (quality over quantity — avoids thin/duplicate content for SEO).

export interface GradientItem {
  type: "gradient";
  cat: "gradients";
  name: string;
  slug: string;
  grad: string;
}
export interface PaletteItem {
  type: "palette";
  cat: "palettes";
  name: string;
  slug: string;
  cols: string[];
}
export interface ShadowItem {
  type: "shadow";
  cat: "shadows";
  name: string;
  slug: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
  color: string;
}
export interface CompItem {
  type: "comp";
  cat: string;
  name: string;
  slug: string;
  html: string;
  css: string;
  js?: string | null;
  bg?: string | null;
}
export type Item = GradientItem | PaletteItem | ShadowItem | CompItem;

export const items: Item[] = [
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Aurora",
    "grad": "linear-gradient(160deg,#0b3b2e,#0e7490)",
    "slug": "gradients-aurora"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Cyanide",
    "grad": "linear-gradient(160deg,#0e2a3a,#2dd4bf)",
    "slug": "gradients-cyanide"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Violet",
    "grad": "linear-gradient(160deg,#241033,#7c3aed)",
    "slug": "gradients-violet"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Amber",
    "grad": "linear-gradient(160deg,#2a1810,#b45309)",
    "slug": "gradients-amber"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Candy",
    "grad": "linear-gradient(135deg,#ff5f9e,#a855f7)",
    "slug": "gradients-candy"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Sunset",
    "grad": "linear-gradient(135deg,#ff7e5f,#feb47b)",
    "slug": "gradients-sunset"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Magma",
    "grad": "linear-gradient(135deg,#3a0ca3,#f72585)",
    "slug": "gradients-magma"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Mint",
    "grad": "linear-gradient(135deg,#0b3b2e,#34d399)",
    "slug": "gradients-mint"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Cobalt",
    "grad": "linear-gradient(160deg,#0e2235,#2563eb)",
    "slug": "gradients-cobalt"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Berry",
    "grad": "linear-gradient(135deg,#4a044e,#d946ef)",
    "slug": "gradients-berry"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Ocean",
    "grad": "linear-gradient(160deg,#03045e,#00b4d8)",
    "slug": "gradients-ocean"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Ember",
    "grad": "linear-gradient(135deg,#7c2d12,#f59e0b)",
    "slug": "gradients-ember"
  },
  {
    "type": "palette",
    "cat": "palettes",
    "name": "Forest",
    "cols": [
      "#0b3b2e",
      "#0e7490",
      "#34d399",
      "#a7f3d0",
      "#ecfdf5"
    ],
    "slug": "palettes-forest"
  },
  {
    "type": "palette",
    "cat": "palettes",
    "name": "Sunset",
    "cols": [
      "#3a0ca3",
      "#7209b7",
      "#f72585",
      "#ff7e5f",
      "#feb47b"
    ],
    "slug": "palettes-sunset"
  },
  {
    "type": "palette",
    "cat": "palettes",
    "name": "Slate",
    "cols": [
      "#0f172a",
      "#1e293b",
      "#475569",
      "#94a3b8",
      "#e2e8f0"
    ],
    "slug": "palettes-slate"
  },
  {
    "type": "palette",
    "cat": "palettes",
    "name": "Candy",
    "cols": [
      "#ff5f9e",
      "#c026d3",
      "#7c3aed",
      "#4361ee",
      "#4cc9f0"
    ],
    "slug": "palettes-candy"
  },
  {
    "type": "palette",
    "cat": "palettes",
    "name": "Earth",
    "cols": [
      "#2a1810",
      "#7c3a12",
      "#b45309",
      "#d4a017",
      "#fef3c7"
    ],
    "slug": "palettes-earth"
  },
  {
    "type": "palette",
    "cat": "palettes",
    "name": "Berry",
    "cols": [
      "#4a044e",
      "#86198f",
      "#d946ef",
      "#f0abfc",
      "#fae8ff"
    ],
    "slug": "palettes-berry"
  },
  {
    "type": "palette",
    "cat": "palettes",
    "name": "Mono",
    "cols": [
      "#0a0a0a",
      "#262626",
      "#525252",
      "#a3a3a3",
      "#f5f5f5"
    ],
    "slug": "palettes-mono"
  },
  {
    "type": "palette",
    "cat": "palettes",
    "name": "Bloom",
    "cols": [
      "#14532d",
      "#16a34a",
      "#86efac",
      "#fde68a",
      "#f59e0b"
    ],
    "slug": "palettes-bloom"
  },
  {
    "type": "comp",
    "cat": "buttons",
    "name": "Glow",
    "html": "<button class=\"b\">Get Started</button>",
    "css": ".b{font:600 16px Outfit,system-ui;padding:14px 30px;border:none;border-radius:12px;color:#fff;background:linear-gradient(120deg,#a855f7,#ec4899);box-shadow:0 10px 30px rgba(168,85,247,.5);cursor:pointer;transition:.25s}.b:hover{transform:translateY(-3px);box-shadow:0 18px 40px rgba(168,85,247,.65)}",
    "slug": "buttons-glow"
  },
  {
    "type": "comp",
    "cat": "buttons",
    "name": "Neon Outline",
    "html": "<button class=\"b\">Launch 🚀</button>",
    "css": ".b{font:600 16px Outfit,system-ui;padding:13px 28px;background:transparent;color:#a855f7;border:1.5px solid #a855f7;border-radius:12px;cursor:pointer;transition:.25s}.b:hover{background:#a855f7;color:#fff;box-shadow:0 0 26px rgba(168,85,247,.7)}",
    "slug": "buttons-neon-outline"
  },
  {
    "type": "comp",
    "cat": "buttons",
    "name": "Shine Sweep",
    "html": "<button class=\"b\">Download</button>",
    "css": ".b{position:relative;overflow:hidden;font:600 16px Outfit,system-ui;padding:14px 30px;border:none;border-radius:12px;color:#fff;background:#7c3aed;cursor:pointer}.b::after{content:\"\";position:absolute;top:0;left:-120%;width:60%;height:100%;background:linear-gradient(120deg,transparent,rgba(255,255,255,.5),transparent);transform:skewX(-20deg);transition:.6s}.b:hover::after{left:140%}",
    "slug": "buttons-shine-sweep"
  },
  {
    "type": "comp",
    "cat": "buttons",
    "name": "3D Push",
    "html": "<button class=\"b\">Press me</button>",
    "css": ".b{font:600 16px Outfit,system-ui;padding:14px 30px;border:none;border-radius:12px;color:#fff;background:#a855f7;box-shadow:0 6px 0 #6d28d9;cursor:pointer;transition:.08s}.b:active{transform:translateY(5px);box-shadow:0 1px 0 #6d28d9}",
    "slug": "buttons-3d-push"
  },
  {
    "type": "comp",
    "cat": "buttons",
    "name": "Gradient Border",
    "html": "<button class=\"b\">Premium</button>",
    "css": ".b{font:600 16px Outfit,system-ui;padding:14px 30px;border:none;border-radius:12px;color:#fff;background:#15111f;position:relative;cursor:pointer}.b::before{content:\"\";position:absolute;inset:0;border-radius:12px;padding:1.5px;background:linear-gradient(120deg,#a855f7,#ec4899);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask-composite:exclude}.b:hover{background:#1d1730}",
    "slug": "buttons-gradient-border"
  },
  {
    "type": "comp",
    "cat": "buttons",
    "name": "Pop Scale",
    "html": "<button class=\"b\">Add to cart</button>",
    "css": ".b{font:600 16px Outfit,system-ui;padding:14px 30px;border:none;border-radius:99px;color:#fff;background:linear-gradient(120deg,#ec4899,#a855f7);cursor:pointer;transition:.18s}.b:hover{transform:scale(1.06)}.b:active{transform:scale(.96)}",
    "slug": "buttons-pop-scale"
  },
  {
    "type": "comp",
    "cat": "toggles",
    "name": "iOS Switch",
    "html": "<label class=\"s\"><input type=\"checkbox\" checked><span></span></label>",
    "css": ".s input{display:none}.s span{display:block;width:60px;height:32px;background:#3a3450;border-radius:99px;position:relative;cursor:pointer;transition:.3s}.s span::after{content:\"\";position:absolute;top:3px;left:3px;width:26px;height:26px;background:#fff;border-radius:50%;transition:.3s}.s input:checked+span{background:#a855f7}.s input:checked+span::after{transform:translateX(28px)}",
    "slug": "toggles-ios-switch"
  },
  {
    "type": "comp",
    "cat": "toggles",
    "name": "Sun / Moon",
    "html": "<label class=\"s\"><input type=\"checkbox\"><span></span></label>",
    "css": ".s input{display:none}.s span{display:block;width:64px;height:32px;border-radius:99px;background:#0ea5e9;position:relative;cursor:pointer;transition:.4s}.s span::after{content:\"☀\";position:absolute;top:2px;left:3px;width:28px;height:28px;background:#fde68a;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:15px;transition:.4s}.s input:checked+span{background:#1e1b4b}.s input:checked+span::after{content:\"🌙\";transform:translateX(31px);background:#cbd5e1}",
    "slug": "toggles-sun-moon"
  },
  {
    "type": "comp",
    "cat": "toggles",
    "name": "Check Pop",
    "html": "<label class=\"s\"><input type=\"checkbox\" checked><span></span></label>",
    "css": ".s input{display:none}.s span{width:30px;height:30px;border-radius:9px;border:2px solid #3a3450;display:flex;align-items:center;justify-content:center;cursor:pointer;transition:.2s}.s span::after{content:\"✓\";color:#fff;font-weight:800;opacity:0;transform:scale(.4);transition:.2s}.s input:checked+span{background:#a855f7;border-color:#a855f7}.s input:checked+span::after{opacity:1;transform:scale(1)}",
    "slug": "toggles-check-pop"
  },
  {
    "type": "comp",
    "cat": "cursors",
    "name": "Glow Trail",
    "html": "<div class=\"stage\">move your mouse<div class=\"blob\"></div></div>",
    "css": ".stage{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:#4a4360;font:600 14px Outfit,system-ui;overflow:hidden;cursor:crosshair}.blob{position:absolute;width:50px;height:50px;border-radius:50%;background:radial-gradient(circle,#a855f7,transparent 70%);pointer-events:none;transform:translate(-50%,-50%)}",
    "js": "var b=document.querySelector(\".blob\"),x=0,y=0,tx=0,ty=0;addEventListener(\"mousemove\",e=>{tx=e.clientX;ty=e.clientY});(function l(){x+=(tx-x)*.12;y+=(ty-y)*.12;b.style.left=x+\"px\";b.style.top=y+\"px\";requestAnimationFrame(l)})()",
    "bg": "#141021",
    "slug": "cursors-glow-trail"
  },
  {
    "type": "comp",
    "cat": "cursors",
    "name": "Spotlight",
    "html": "<div class=\"stage\">move your mouse</div>",
    "css": ".stage{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:#4a4360;font:600 14px Outfit,system-ui;cursor:crosshair;background:#141021}",
    "js": "var s=document.querySelector(\".stage\");addEventListener(\"mousemove\",e=>{s.style.background=\"radial-gradient(220px circle at \"+e.clientX+\"px \"+e.clientY+\"px,rgba(168,85,247,.25),#141021)\"})",
    "bg": "#141021",
    "slug": "cursors-spotlight"
  },
  {
    "type": "comp",
    "cat": "cursors",
    "name": "Magnetic Ring",
    "html": "<div class=\"stage\">move your mouse<div class=\"ring\"></div><div class=\"dot\"></div></div>",
    "css": ".stage{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:#4a4360;font:600 14px Outfit,system-ui;cursor:crosshair;overflow:hidden}.ring{position:absolute;width:40px;height:40px;border:2px solid #a855f7;border-radius:50%;pointer-events:none;transform:translate(-50%,-50%)}.dot{position:absolute;width:6px;height:6px;background:#ec4899;border-radius:50%;pointer-events:none;transform:translate(-50%,-50%)}",
    "js": "var r=document.querySelector(\".ring\"),d=document.querySelector(\".dot\"),x=0,y=0,rx=0,ry=0;addEventListener(\"mousemove\",e=>{x=e.clientX;y=e.clientY;d.style.left=x+\"px\";d.style.top=y+\"px\"});(function l(){rx+=(x-rx)*.15;ry+=(y-ry)*.15;r.style.left=rx+\"px\";r.style.top=ry+\"px\";requestAnimationFrame(l)})()",
    "bg": "#141021",
    "slug": "cursors-magnetic-ring"
  },
  {
    "type": "shadow",
    "cat": "shadows",
    "name": "Soft",
    "x": 0,
    "y": 12,
    "blur": 30,
    "spread": -6,
    "color": "rgba(0,0,0,.35)",
    "slug": "shadows-soft"
  },
  {
    "type": "shadow",
    "cat": "shadows",
    "name": "Floating",
    "x": 0,
    "y": 24,
    "blur": 50,
    "spread": -12,
    "color": "rgba(0,0,0,.4)",
    "slug": "shadows-floating"
  },
  {
    "type": "shadow",
    "cat": "shadows",
    "name": "Glow Violet",
    "x": 0,
    "y": 0,
    "blur": 40,
    "spread": 0,
    "color": "rgba(168,85,247,.6)",
    "slug": "shadows-glow-violet"
  },
  {
    "type": "shadow",
    "cat": "shadows",
    "name": "Glow Pink",
    "x": 0,
    "y": 0,
    "blur": 40,
    "spread": 0,
    "color": "rgba(236,72,153,.55)",
    "slug": "shadows-glow-pink"
  },
  {
    "type": "shadow",
    "cat": "shadows",
    "name": "Hard Offset",
    "x": 10,
    "y": 10,
    "blur": 0,
    "spread": 0,
    "color": "#a855f7",
    "slug": "shadows-hard-offset"
  },
  {
    "type": "shadow",
    "cat": "shadows",
    "name": "Deep",
    "x": 0,
    "y": 30,
    "blur": 60,
    "spread": -10,
    "color": "rgba(0,0,0,.55)",
    "slug": "shadows-deep"
  },
  {
    "type": "comp",
    "cat": "loaders",
    "name": "Spinner",
    "html": "<div class=\"ld\"></div>",
    "css": ".ld{width:40px;height:40px;border:4px solid #2a2440;border-top-color:#a855f7;border-radius:50%;animation:sp 1s linear infinite}@keyframes sp{to{transform:rotate(360deg)}}",
    "slug": "loaders-spinner"
  },
  {
    "type": "comp",
    "cat": "loaders",
    "name": "Dual Ring",
    "html": "<div class=\"ld\"></div>",
    "css": ".ld{width:44px;height:44px;border-radius:50%;border:4px solid transparent;border-top-color:#a855f7;border-bottom-color:#ec4899;animation:sp 1.1s ease infinite}@keyframes sp{to{transform:rotate(360deg)}}",
    "slug": "loaders-dual-ring"
  },
  {
    "type": "comp",
    "cat": "loaders",
    "name": "Bouncing Dots",
    "html": "<div class=\"ld\"><i></i><i></i><i></i></div>",
    "css": ".ld{display:flex;gap:8px}.ld i{width:12px;height:12px;border-radius:50%;background:#a855f7;animation:bn .6s ease infinite}.ld i:nth-child(2){animation-delay:.15s}.ld i:nth-child(3){animation-delay:.3s}@keyframes bn{0%,100%{transform:translateY(0);opacity:.5}50%{transform:translateY(-12px);opacity:1}}",
    "slug": "loaders-bouncing-dots"
  },
  {
    "type": "comp",
    "cat": "loaders",
    "name": "Pulse Ring",
    "html": "<div class=\"ld\"></div>",
    "css": ".ld{width:36px;height:36px;border-radius:50%;background:#a855f7;animation:pl 1.2s ease-out infinite}@keyframes pl{0%{box-shadow:0 0 0 0 rgba(168,85,247,.6)}100%{box-shadow:0 0 0 24px rgba(168,85,247,0)}}",
    "slug": "loaders-pulse-ring"
  },
  {
    "type": "comp",
    "cat": "loaders",
    "name": "Bars",
    "html": "<div class=\"ld\"><i></i><i></i><i></i><i></i></div>",
    "css": ".ld{display:flex;gap:5px;align-items:flex-end;height:40px}.ld i{width:7px;height:100%;background:linear-gradient(#a855f7,#ec4899);border-radius:4px;animation:br 1s ease infinite}.ld i:nth-child(2){animation-delay:.15s}.ld i:nth-child(3){animation-delay:.3s}.ld i:nth-child(4){animation-delay:.45s}@keyframes br{0%,100%{transform:scaleY(.4)}50%{transform:scaleY(1)}}",
    "slug": "loaders-bars"
  },
  {
    "type": "comp",
    "cat": "textfx",
    "name": "Gradient Text",
    "html": "<div class=\"t\">Beautiful</div>",
    "css": ".t{font:800 44px Outfit,system-ui;background:linear-gradient(120deg,#a855f7,#ec4899);-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent}",
    "slug": "textfx-gradient-text"
  },
  {
    "type": "comp",
    "cat": "textfx",
    "name": "Shimmer",
    "html": "<div class=\"t\">Shimmer</div>",
    "css": ".t{font:800 44px Outfit,system-ui;background:linear-gradient(90deg,#4a4360,#fff,#4a4360);background-size:200% auto;-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;animation:sh 2.5s linear infinite}@keyframes sh{to{background-position:200% center}}",
    "slug": "textfx-shimmer"
  },
  {
    "type": "comp",
    "cat": "textfx",
    "name": "Neon Glow",
    "html": "<div class=\"t\">NEON</div>",
    "css": ".t{font:800 44px Outfit,system-ui;color:#fff;text-shadow:0 0 6px #a855f7,0 0 16px #a855f7,0 0 34px #ec4899}",
    "slug": "textfx-neon-glow"
  },
  {
    "type": "comp",
    "cat": "textfx",
    "name": "Outline",
    "html": "<div class=\"t\">Outline</div>",
    "css": ".t{font:800 44px Outfit,system-ui;color:transparent;-webkit-text-stroke:1.5px #a855f7}",
    "slug": "textfx-outline"
  },
  {
    "type": "comp",
    "cat": "textfx",
    "name": "Glitch",
    "html": "<div class=\"t\">glitch</div>",
    "css": ".t{font:800 44px Outfit,system-ui;color:#fff;position:relative}.t::before,.t::after{content:\"glitch\";position:absolute;inset:0}.t::before{color:#a855f7;animation:gl 2s infinite}.t::after{color:#ec4899;animation:gl 2s infinite reverse}@keyframes gl{0%,100%{clip-path:inset(0);transform:translate(0)}20%{transform:translate(-3px,1px)}40%{transform:translate(3px,-1px)}}",
    "slug": "textfx-glitch"
  },
  {
    "type": "comp",
    "cat": "cards",
    "name": "Glassmorphism",
    "html": "<div class=\"gl\">Glass</div>",
    "css": ".gl{width:160px;height:100px;border-radius:18px;background:rgba(255,255,255,.08);backdrop-filter:blur(12px);border:1px solid rgba(255,255,255,.18);display:flex;align-items:center;justify-content:center;color:#fff;font:600 16px Outfit,system-ui;box-shadow:0 10px 40px rgba(0,0,0,.3)}",
    "js": null,
    "bg": "linear-gradient(135deg,#a855f7,#ec4899)",
    "slug": "cards-glassmorphism"
  },
  {
    "type": "comp",
    "cat": "cards",
    "name": "Gradient Border",
    "html": "<div class=\"gb\">Card</div>",
    "css": ".gb{width:160px;height:100px;border-radius:18px;background:#15111f;position:relative;display:flex;align-items:center;justify-content:center;color:#fff;font:600 16px Outfit,system-ui}.gb::before{content:\"\";position:absolute;inset:0;border-radius:18px;padding:1.5px;background:linear-gradient(120deg,#a855f7,#ec4899);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask-composite:exclude}",
    "slug": "cards-gradient-border"
  },
  {
    "type": "comp",
    "cat": "cards",
    "name": "Neumorphic",
    "html": "<div class=\"nu\">Soft</div>",
    "css": ".nu{width:150px;height:100px;border-radius:22px;background:#e0e0ec;box-shadow:9px 9px 18px #bcbcC8,-9px -9px 18px #ffffff;display:flex;align-items:center;justify-content:center;color:#6d28d9;font:600 16px Outfit,system-ui}",
    "js": null,
    "bg": "#e0e0ec",
    "slug": "cards-neumorphic"
  },
  {
    "type": "comp",
    "cat": "cards",
    "name": "Spotlight Hover",
    "html": "<div class=\"sp\">Hover me</div>",
    "css": ".sp{width:170px;height:110px;border-radius:18px;background:#15111f;border:1px solid #241d38;display:flex;align-items:center;justify-content:center;color:#cfc7e8;font:600 15px Outfit,system-ui;position:relative;overflow:hidden;cursor:pointer}.sp::before{content:\"\";position:absolute;inset:0;background:radial-gradient(160px circle at var(--x,50%) var(--y,50%),rgba(168,85,247,.35),transparent 60%);opacity:0;transition:.3s}.sp:hover::before{opacity:1}",
    "js": "var s=document.querySelector(\".sp\");s.addEventListener(\"mousemove\",e=>{var r=s.getBoundingClientRect();s.style.setProperty(\"--x\",(e.clientX-r.left)+\"px\");s.style.setProperty(\"--y\",(e.clientY-r.top)+\"px\")})",
    "bg": "#141021",
    "slug": "cards-spotlight-hover"
  },
  {
    "type": "comp",
    "cat": "backgrounds",
    "name": "Aurora",
    "html": "<div class=\"bg\"></div>",
    "css": ".bg{width:100%;height:100%;background:linear-gradient(125deg,#0d0a17,#2a1248,#3d1040,#0d0a17);background-size:400% 400%;animation:au 12s ease infinite}@keyframes au{0%,100%{background-position:0% 50%}50%{background-position:100% 50%}}",
    "slug": "backgrounds-aurora"
  },
  {
    "type": "comp",
    "cat": "backgrounds",
    "name": "Dot Grid",
    "html": "<div class=\"bg\"></div>",
    "css": ".bg{width:100%;height:100%;background:#0d0a17;background-image:radial-gradient(rgba(168,85,247,.4) 1px,transparent 1px);background-size:22px 22px}",
    "slug": "backgrounds-dot-grid"
  },
  {
    "type": "comp",
    "cat": "backgrounds",
    "name": "Mesh",
    "html": "<div class=\"bg\"></div>",
    "css": ".bg{width:100%;height:100%;background:radial-gradient(at 20% 20%,#7c3aed 0,transparent 50%),radial-gradient(at 80% 30%,#ec4899 0,transparent 50%),radial-gradient(at 50% 80%,#2563eb 0,transparent 50%),#0d0a17}",
    "slug": "backgrounds-mesh"
  },
  {
    "type": "comp",
    "cat": "backgrounds",
    "name": "Stripes",
    "html": "<div class=\"bg\"></div>",
    "css": ".bg{width:100%;height:100%;background:repeating-linear-gradient(45deg,#15111f,#15111f 14px,#1d1730 14px,#1d1730 28px)}",
    "slug": "backgrounds-stripes"
  },
  {
    "type": "comp",
    "cat": "backgrounds",
    "name": "Grid Lines",
    "html": "<div class=\"bg\"></div>",
    "css": ".bg{width:100%;height:100%;background:#0d0a17;background-image:linear-gradient(rgba(168,85,247,.12) 1px,transparent 1px),linear-gradient(90deg,rgba(168,85,247,.12) 1px,transparent 1px);background-size:28px 28px}",
    "slug": "backgrounds-grid-lines"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Peach",
    "grad": "linear-gradient(135deg,#ff9a9e,#fecfef)",
    "slug": "gradients-peach"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Twilight",
    "grad": "linear-gradient(160deg,#0f0c29,#302b63)",
    "slug": "gradients-twilight"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Lime",
    "grad": "linear-gradient(135deg,#166534,#bef264)",
    "slug": "gradients-lime"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Rosegold",
    "grad": "linear-gradient(135deg,#b76e79,#eacda3)",
    "slug": "gradients-rosegold"
  },
  {
    "type": "palette",
    "cat": "palettes",
    "name": "Tide",
    "cols": [
      "#03045e",
      "#0077b6",
      "#00b4d8",
      "#90e0ef",
      "#caf0f8"
    ],
    "slug": "palettes-tide"
  },
  {
    "type": "palette",
    "cat": "palettes",
    "name": "Dusk",
    "cols": [
      "#2b2d42",
      "#8d99ae",
      "#edf2f4",
      "#ef233c",
      "#d90429"
    ],
    "slug": "palettes-dusk"
  },
  {
    "type": "comp",
    "cat": "buttons",
    "name": "Ghost",
    "html": "<button class=\"b\">Cancel</button>",
    "css": ".b{font:600 16px Outfit,system-ui;padding:13px 28px;background:rgba(168,85,247,.08);color:#c084fc;border:1px solid rgba(168,85,247,.3);border-radius:12px;cursor:pointer;transition:.2s}.b:hover{background:rgba(168,85,247,.18)}",
    "slug": "buttons-ghost"
  },
  {
    "type": "comp",
    "cat": "buttons",
    "name": "Arrow Slide",
    "html": "<button class=\"b\">Next <span>→</span></button>",
    "css": ".b{font:600 16px Outfit,system-ui;padding:14px 28px;border:none;border-radius:12px;color:#fff;background:#7c3aed;cursor:pointer;display:inline-flex;align-items:center;gap:8px}.b span{transition:.25s}.b:hover span{transform:translateX(6px)}",
    "slug": "buttons-arrow-slide"
  },
  {
    "type": "comp",
    "cat": "inputs",
    "name": "Glow Focus",
    "html": "<input class=\"i\" placeholder=\"Email address\">",
    "css": ".i{font:500 15px Outfit,system-ui;padding:13px 16px;width:230px;background:#15111f;border:1.5px solid #2a2440;border-radius:12px;color:#fff;outline:none;transition:.25s}.i::placeholder{color:#6b6486}.i:focus{border-color:#a855f7;box-shadow:0 0 0 4px rgba(168,85,247,.18)}",
    "js": null,
    "bg": "#141021",
    "slug": "inputs-glow-focus"
  },
  {
    "type": "comp",
    "cat": "inputs",
    "name": "Underline",
    "html": "<input class=\"i\" placeholder=\"Your name\">",
    "css": ".i{font:500 15px Outfit,system-ui;padding:10px 2px;width:230px;background:none;border:none;border-bottom:2px solid #2a2440;color:#fff;outline:none;transition:.25s}.i::placeholder{color:#6b6486}.i:focus{border-color:#ec4899}",
    "js": null,
    "bg": "#141021",
    "slug": "inputs-underline"
  },
  {
    "type": "comp",
    "cat": "inputs",
    "name": "Search Bar",
    "html": "<div class=\"sw\"><span>⌕</span><input placeholder=\"Search…\"></div>",
    "css": ".sw{display:flex;align-items:center;gap:8px;background:#15111f;border:1.5px solid #2a2440;border-radius:12px;padding:11px 14px;width:230px;transition:.25s}.sw span{color:#6b6486}.sw input{flex:1;background:none;border:none;outline:none;color:#fff;font:500 14px Outfit,system-ui}.sw:focus-within{border-color:#a855f7}",
    "js": null,
    "bg": "#141021",
    "slug": "inputs-search-bar"
  },
  {
    "type": "comp",
    "cat": "badges",
    "name": "Pill",
    "html": "<span class=\"bg\">New</span>",
    "css": ".bg{font:600 13px Outfit,system-ui;padding:5px 14px;border-radius:999px;background:rgba(168,85,247,.15);color:#c084fc;border:1px solid rgba(168,85,247,.4)}",
    "js": null,
    "bg": "#141021",
    "slug": "badges-pill"
  },
  {
    "type": "comp",
    "cat": "badges",
    "name": "Status Dot",
    "html": "<span class=\"bg\"><i></i>Online</span>",
    "css": ".bg{font:600 13px Outfit,system-ui;display:inline-flex;align-items:center;gap:7px;padding:6px 14px;border-radius:999px;background:#15111f;border:1px solid #2a2440;color:#e8e4f3}.bg i{width:8px;height:8px;border-radius:50%;background:#34d399;box-shadow:0 0 8px #34d399;animation:bl 1.5s infinite}@keyframes bl{50%{opacity:.4}}",
    "js": null,
    "bg": "#141021",
    "slug": "badges-status-dot"
  },
  {
    "type": "comp",
    "cat": "badges",
    "name": "Gradient Tag",
    "html": "<span class=\"bg\">PRO</span>",
    "css": ".bg{font:700 12px Outfit,system-ui;letter-spacing:.08em;padding:5px 13px;border-radius:8px;background:linear-gradient(120deg,#a855f7,#ec4899);color:#fff}",
    "js": null,
    "bg": "#141021",
    "slug": "badges-gradient-tag"
  },
  {
    "type": "comp",
    "cat": "loaders",
    "name": "Ripple",
    "html": "<div class=\"ld\"></div>",
    "css": ".ld{width:44px;height:44px;border-radius:50%;border:3px solid #a855f7;animation:rp 1s ease-out infinite}@keyframes rp{0%{transform:scale(.3);opacity:1}100%{transform:scale(1);opacity:0}}",
    "slug": "loaders-ripple"
  },
  {
    "type": "comp",
    "cat": "textfx",
    "name": "Underline Grow",
    "html": "<div class=\"t\">Hover me</div>",
    "css": ".t{font:800 40px Outfit,system-ui;color:#fff;position:relative;cursor:pointer;display:inline-block}.t::after{content:\"\";position:absolute;left:0;bottom:-4px;width:100%;height:4px;background:linear-gradient(120deg,#a855f7,#ec4899);border-radius:4px;transform:scaleX(0);transform-origin:left;transition:.3s}.t:hover::after{transform:scaleX(1)}",
    "slug": "textfx-underline-grow"
  },
  {
    "type": "comp",
    "cat": "cards",
    "name": "Stat Card",
    "html": "<div class=\"sc\"><div class=\"n\">2.4k</div><div class=\"l\">Downloads</div></div>",
    "css": ".sc{width:160px;padding:22px;border-radius:18px;background:linear-gradient(160deg,#1a1330,#15111f);border:1px solid #2a2440}.sc .n{font:800 30px Outfit,system-ui;background:linear-gradient(120deg,#a855f7,#ec4899);-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent}.sc .l{font:500 13px Outfit,system-ui;color:#857f9c;margin-top:4px}",
    "slug": "cards-stat-card"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Plum Wine",
    "grad": "linear-gradient(135deg,#42275a,#734b6d)",
    "slug": "gradients-plum-wine"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Sea Breeze",
    "grad": "linear-gradient(135deg,#1cb5e0,#000851)",
    "slug": "gradients-sea-breeze"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Mango",
    "grad": "linear-gradient(135deg,#ffe259,#ffa751)",
    "slug": "gradients-mango"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Royal",
    "grad": "linear-gradient(135deg,#141e30,#243b55)",
    "slug": "gradients-royal"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Cosmic",
    "grad": "linear-gradient(135deg,#ff00cc,#333399)",
    "slug": "gradients-cosmic"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Lush",
    "grad": "linear-gradient(135deg,#56ab2f,#a8e063)",
    "slug": "gradients-lush"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Cherry",
    "grad": "linear-gradient(135deg,#eb3349,#f45c43)",
    "slug": "gradients-cherry"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Frost",
    "grad": "linear-gradient(135deg,#000428,#004e92)",
    "slug": "gradients-frost"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Peachy",
    "grad": "linear-gradient(135deg,#ed4264,#ffedbc)",
    "slug": "gradients-peachy"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Emerald",
    "grad": "linear-gradient(135deg,#348f50,#56b4d3)",
    "slug": "gradients-emerald"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Grape",
    "grad": "linear-gradient(135deg,#6a3093,#a044ff)",
    "slug": "gradients-grape"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Flare",
    "grad": "linear-gradient(135deg,#f12711,#f5af19)",
    "slug": "gradients-flare"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Steel",
    "grad": "linear-gradient(135deg,#bdc3c7,#2c3e50)",
    "slug": "gradients-steel"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Bloodfire",
    "grad": "linear-gradient(135deg,#cb2d3e,#ef473a)",
    "slug": "gradients-bloodfire"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Aqua",
    "grad": "linear-gradient(135deg,#13547a,#80d0c7)",
    "slug": "gradients-aqua"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Moonlit",
    "grad": "linear-gradient(135deg,#0f2027,#2c5364)",
    "slug": "gradients-moonlit"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Coral",
    "grad": "linear-gradient(135deg,#ff9966,#ff5e62)",
    "slug": "gradients-coral"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Deep Sea",
    "grad": "linear-gradient(135deg,#2c3e50,#4ca1af)",
    "slug": "gradients-deep-sea"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Pinky",
    "grad": "linear-gradient(135deg,#ee9ca7,#ffdde1)",
    "slug": "gradients-pinky"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Nightfall",
    "grad": "linear-gradient(135deg,#191654,#43c6ac)",
    "slug": "gradients-nightfall"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Tangerine",
    "grad": "linear-gradient(135deg,#f83600,#f9d423)",
    "slug": "gradients-tangerine"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Lavender",
    "grad": "linear-gradient(135deg,#a18cd1,#fbc2eb)",
    "slug": "gradients-lavender"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Toxic",
    "grad": "linear-gradient(135deg,#00b09b,#96c93d)",
    "slug": "gradients-toxic"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Ruby",
    "grad": "linear-gradient(135deg,#b31217,#e52d27)",
    "slug": "gradients-ruby"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Skyfall",
    "grad": "linear-gradient(135deg,#647dee,#7f53ac)",
    "slug": "gradients-skyfall"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Mojito",
    "grad": "linear-gradient(135deg,#1d976c,#93f9b9)",
    "slug": "gradients-mojito"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Fuchsia",
    "grad": "linear-gradient(135deg,#c31432,#240b36)",
    "slug": "gradients-fuchsia"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Indigo Night",
    "grad": "linear-gradient(135deg,#1a2980,#26d0ce)",
    "slug": "gradients-indigo-night"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Honey",
    "grad": "linear-gradient(135deg,#f7971e,#ffd200)",
    "slug": "gradients-honey"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Velvet",
    "grad": "linear-gradient(135deg,#41295a,#2f0743)",
    "slug": "gradients-velvet"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Teal Love",
    "grad": "linear-gradient(135deg,#11998e,#38ef7d)",
    "slug": "gradients-teal-love"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Crimson",
    "grad": "linear-gradient(135deg,#642b73,#c6426e)",
    "slug": "gradients-crimson"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Glacier",
    "grad": "linear-gradient(135deg,#74ebd5,#acb6e5)",
    "slug": "gradients-glacier"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Sunburn",
    "grad": "linear-gradient(135deg,#fc4a1a,#f7b733)",
    "slug": "gradients-sunburn"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Orchid",
    "grad": "linear-gradient(135deg,#da22ff,#9733ee)",
    "slug": "gradients-orchid"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Lagoon",
    "grad": "linear-gradient(135deg,#43cea2,#185a9d)",
    "slug": "gradients-lagoon"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Dawn Sky",
    "grad": "linear-gradient(135deg,#fbc2eb,#a6c1ee)",
    "slug": "gradients-dawn-sky"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Magenta",
    "grad": "linear-gradient(135deg,#ee0979,#ff6a00)",
    "slug": "gradients-magenta"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Northern",
    "grad": "linear-gradient(135deg,#4facfe,#00f2fe)",
    "slug": "gradients-northern"
  },
  {
    "type": "gradient",
    "cat": "gradients",
    "name": "Rosewater",
    "grad": "linear-gradient(135deg,#e55d87,#5fc3e4)",
    "slug": "gradients-rosewater"
  }
];
